### ISSUE TITLE
大佬，这个项目可以远程帮我跑一下吗，有偿

### ISSUE THREAD

**Issue by 11days** [Advancedpawn2020/cinema#6]
电脑已经下了vscode, IDEA, MySQL, Redis, Docker，都跑过一些东西了，学校期末要交个大作业，但是Java的环境没配，可以有偿远程配下环境，然后跑通这个项目就行

**Comment by Zejoo** [comment]
收到！会在查阅后尽快给您回复，谢谢！

**Comment by 11days** [comment]
然后，其实另外找过一个项目跑了下，但是Maven和Pack of Java这些插件下了后，报错100多个，，，主要想配一下环境，,,,vscode或者IDEA都行，远程的话可以用qq的
